### ISSUE TITLE
Copy paste issue

### ISSUE THREAD

**Issue by LIVEGUYS** [platz1de/EasyEdit#112] opened 2024-03-27 01:56 UTC
When I do //cut than it gone the land I know it's gone ok that's nice but when I do //flip it's flipped also but when I do //paste doesn't show any structure only shows (numbers) blocks has been placed! (Numbers) I means I forgot the blocks how many are there! That's why (numbers) it's shows block has been placed but no structure?

**Comment by LIVEGUYS** [comment] 2024-03-27 02:12
Update the plugin to API 5.13.0

**Comment by platz1de** [comment] 2024-03-27 12:51
I can't reproduce this, which version of EasyEdit are you using?
Also is there anything in the console?

**Comment by LIVEGUYS** [comment] 2024-03-30 16:03
3.1.0 newest update! When I do /paste doesn't show the structure I copied /copy by /flip than i did /paste doesn't work doesn't show in live console I need to check log

**Comment by LIVEGUYS** [comment] 2024-03-30 16:05
I change the plugin api into 5.12.0 to 5.13.0 in the plugin.yml in easyedit 3.1.0 in this version!

**Comment by LIVEGUYS** [comment] 2024-03-30 16:15
I did check recently doesn't show anything error in the console and even in the log file

**Comment by platz1de** [comment] 2024-04-03 21:01
Were you looking up while flipping? If so i'll close this in favor of #116

**Comment by LIVEGUYS** [comment] 2024-04-04 00:41
Yep flip is not working pls fix same problem

**Comment by LIVEGUYS** [comment] 2024-04-06 01:01
Same problem

**Closed** 2024-04-06 01:01 UTC
Labels: awaiting response
