### ISSUE TITLE
When I copy big structure and try to rotate it, it can't be rotated.

### ISSUE THREAD

**Issue by mtugb** [platz1de/EasyEdit#88] opened 2023-10-08 13:06 UTC
Error(in console):
![image](https://github.com/platz1de/EasyEdit/assets/71925019/46acf35f-fd11-4e16-90fc-843f835a4e09)

Message in minecraft:
![image](https://github.com/platz1de/EasyEdit/assets/71925019/be3b5120-10c8-4fb6-983d-0e77bb73cb2c)

**Comment by platz1de** [comment] 2023-10-08 13:14
Duplicate of #82

**Closed** 2023-10-08 13:14 UTC
