### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AraaCuteUwU** [platz1de/EasyEdit#56] opened 2023-07-04 03:06 UTC
Error: "Typed static property platz1de\EasyEdit\world\HeightMapCache::$ignore must not be accessed before initialization" (EXCEPTION) in "plugins/EasyEdit/src/platz1de/EasyEdit/world/HeightMapCache" at line 256

**Comment by platz1de** [comment] 2023-07-06 13:18
Duplicate of #44

**Closed** 2023-07-06 13:18 UTC
Labels: bug
