### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by CoolCuzzy** [platz1de/EasyEdit#58] opened 2023-07-06 13:14 UTC
![image](https://github.com/platz1de/EasyEdit/assets/51475531/6c88759b-fdd6-4b21-9507-1fd69e159bb8)

im not exactly sure what my builder did but this is the error.

**Comment by platz1de** [comment] 2023-07-06 13:19
Duplicate of #44

**Closed** 2023-07-06 13:19 UTC
