### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gamegam** [platz1de/EasyEdit#77] opened 2023-08-18 09:33 UTC
[17:31:12.306] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: plug Plugins
[17:31:12.308] [Server thread/CRITICAL]: pocketmine\data\bedrock\block\convert\UnsupportedBlockStateException: "Unknown block tag 10306" (EXCEPTION) in "plugins/EasyEdit-master/src/platz1de/EasyEdit/convert/BlockTagManager" at line 93

**Comment by platz1de** [comment] 2023-08-18 11:52
Please post the full error message
Probably a duplicate of one of the resolved issues too

**Comment by LIVEGUYS** [comment] 2023-08-31 20:48
This error fixed close this issue

**Closed** 2023-09-13 12:57 UTC
Labels: awaiting response
