### ISSUE TITLE
//replace crash

### ISSUE THREAD

**Issue by roimee6** [platz1de/EasyEdit#65] opened 2023-07-12 20:10 UTC
When you replace with non-existent blocks (or just with a spelling mistake), the server crashes.
```
[20:08:26.908] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: MaXoooZ
[20:08:26.908] [Server thread/CRITICAL]: Error: "Typed static property platz1de\EasyEdit\world\HeightMapCache::$ignore must not be accessed before initialization" (EXCEPTION) in "plugins/EasyEdit.phar/src/platz1de/EasyEdit/world/HeightMapCache" at line 256
--- Stack trace ---
  #0 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/defaults/selection/ReplaceCommand(46): platz1de\EasyEdit\world\HeightMapCache::getIgnore()
  #1 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/flags/CommandFlagParser(78): platz1de\EasyEdit\command\defaults\selection\ReplaceCommand->parseArguments(object platz1de\EasyEdit\command\flags\CommandFlagCollection#125082, object platz1de\EasyEdit\session\Session#107206, array[1])
  #2 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/CommandManager(46): platz1de\EasyEdit\command\flags\CommandFlagParser::parseFlags(object platz1de\EasyEdit\command\defaults\selection\ReplaceCommand#151526, array[1], object platz1de\EasyEdit\session\Session#107206)
  #3 plugins/EasyEdit.phar/src/platz1de/EasyEdit/command/EasyEditCommand(46): platz1de\EasyEdit\command\CommandManager::processCommand(object platz1de\EasyEdit\command\defaults\selection\ReplaceCommand#151526, array[1], object MaXoooZ\Util\entity\Player#122375)
  #4 pmsrc/src/command/SimpleCommandMap(212): platz1de\EasyEdit\command\EasyEditCommand->execute(object MaXoooZ\Util\entity\Player#122375, string[8] /replace, array[1])
  #5 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object MaXoooZ\Util\entity\Player#122375, string[25] /replace spruce_planksair)
  #6 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object MaXoooZ\Util\entity\Player#122375, string[25] /replace spruce_planksair)
  #7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(157): pocketmine\player\Player->chat(string[27] .//replace spruce_planksair)
  #8 pmsrc/vendor/pocketmine/bedrock-protocol/src/TextPacket(164): pocketmine\network\mcpe\handler\InGamePacketHandler->handleText(object pocketmine\network\mcpe\protocol\TextPacket#140628)
  #9 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\TextPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#111476)
  #10 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\TextPacket#140628, string[57] ....MaXoooZ..//replace spruce_planksair.2535460509886290.)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[58] ..dd`.M........./J-.ILNU(.(*MN..r....3...L.MM..L.,-,..,...)
  #12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[67] .K"K.....:}......P...UX....@...u=uj..l..F...o.3i.@.S. F1P..O\.M...l)
  #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#10647)
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #15 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #17 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1689192506.9488)
  #18 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #19 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[24] /home/debian/srv/kitmap/, string[32] /home/debian/srv/kitmap/plugins/)
  #20 pmsrc/src/PocketMine(357): pocketmine\server()
  #21 pmsrc(11): require(string[68] phar:///home/debian/srv/kitmap/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[20:08:26.908] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[20:08:26.913] [Server thread/EMERGENCY]: Please upload the "/home/debian/srv/kitmap/crashdumps/Wed_Jul_12-22.08.26-CEST_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[20:08:27.448] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/8952227 or use the ID #8952227.
```

**Comment by platz1de** [comment] 2023-07-12 20:14
Duplicate of #44 (The issue occurs when only specifying one block)

**Closed by platz1de** 2023-07-12 20:14 UTC
Labels: duplicate
