### ISSUE TITLE
//load schematic

### ISSUE THREAD

**Issue by FortniteProCracked** [platz1de/EasyEdit#50] opened 2023-06-26 17:58 UTC
when i try to load my schematic, it comes up with this error. 
![image](https://github.com/platz1de/EasyEdit/assets/137822170/e771f1a0-770e-4f81-8a3e-59e3a6262b53)

"Your task crashed, please report this!
No Bytes Left in Buffer"

**Comment by platz1de** [comment] 2023-06-26 18:01
Duplicate of #47

**Closed by platz1de** 2023-06-26 18:01 UTC
