### ISSUE TITLE
Add in category of brush add the replace.

### ISSUE THREAD

**Issue by LIVEGUYS** [platz1de/EasyEdit#123] opened 2024-10-28 23:56 UTC
When brush in radius using replace will be good and better!

**Comment by platz1de** [comment] 2024-10-29 14:39
Replace Brushes can already be created using [checkblock patterns](https://github.com/platz1de/EasyEdit/wiki/Checkblock-Pattern), e.g. `//brush sphere 10 block;dirt(grass_block)` to replace dirt with grass.
(Duplicate of #71)

**Closed by platz1de** 2024-10-29 14:39 UTC
