### ISSUE TITLE
Using wrong tags will crash server 

### ISSUE THREAD

**Issue by CoolCuzzy** [platz1de/EasyEdit#63] opened 2023-07-11 06:00 UTC
Using unknown block tag will crash server…

![image](https://github.com/platz1de/EasyEdit/assets/51475531/481b7540-873e-4f5e-b906-20a90a15a277)

**Comment by platz1de** [comment] 2023-07-11 11:53
Duplicate of #60

**Closed by platz1de** 2023-07-11 11:53 UTC
