### ISSUE TITLE
//fix add

### ISSUE THREAD

**Issue by gamegam** [platz1de/EasyEdit#93] opened 2023-10-21 06:26 UTC
The fix command is an error block in the specified place, and when you install a rail in Java and import the map from PM, it appears to be an update block or rail. Put in the function to hit this!

**Comment by platz1de** [comment] 2023-10-21 09:29
Duplicate of #24
Also try using schematics when transfering data between versions, they support conversion

**Closed by platz1de** 2023-10-21 09:29 UTC
