### ISSUE TITLE
//rotate is broken

### ISSUE THREAD

**Issue by CoolCuzzy** [platz1de/EasyEdit#92] opened 2023-10-21 03:03 UTC
Essentially when i attempt to //rotate a large or even medium or any size above like a 5 by 5 this error occurs

--- Stack trace ---
  #0 /home/container/plugins/EasyEdit-master/src/platz1de/EasyEdit/task/ExecutableTask(39): platz1de\EasyEdit\task\DynamicStoredRotateTask->executeInternal()
  #1 /home/container/plugins/EasyEdit-master/src/platz1de/EasyEdit/thread/EditThread(76): platz1de\EasyEdit\task\ExecutableTask->run()
  #2 pmsrc/src/thread/CommonThreadPartsTrait(109): platz1de\EasyEdit\thread\EditThread->onRun()
  #3 (): pocketmine\thread\Thread->run()
--- End of exception information --

Rotate is such an important command that just isnt working!!

**Comment by platz1de** [comment] 2023-10-21 09:27
Duplicate of #82 and fixed on the dev branch
Use the newest dev build from poggit

**Closed by platz1de** 2023-10-21 09:27 UTC
