### ISSUE TITLE
Bug //rotate

### ISSUE THREAD

**Issue by thedrewen** [platz1de/EasyEdit#96] opened 2023-11-12 19:09 UTC
When I copy an area that is too large I cannot rotate the area.

**Comment by platz1de** [comment] 2023-11-12 19:11
Duplicate of #82 and fixed on the dev branch
Use the newest dev build from poggit

**Closed by platz1de** 2023-11-12 19:11 UTC
Labels: duplicate

**Comment by thedrewen** [comment] 2023-11-12 20:26
> Duplicate of #82 and fixed on the dev branch Use the newest dev build from poggit

I don't understand. Have you a link ?

**Comment by platz1de** [comment] 2023-11-12 20:27
https://poggit.pmmp.io/r/227164/EasyEdit_dev-492.phar

**Comment by thedrewen** [comment] 2023-11-12 20:36
thx goodbye.
