### ISSUE TITLE
crash in schematic

### ISSUE THREAD

**Issue by ByNamles** [platz1de/EasyEdit#61] opened 2023-07-09 10:57 UTC
[10:53:49.438] [EasyEdit editing thread/CRITICAL]: pocketmine\utils\BinaryDataException: "No bytes left in buffer" (EXCEPTION) in "pmsrc/vendor/pocketmine/binaryutils/src/Binary" at line 407
--- Stack trace ---
  #0 /root/plugins/EasyEdit-master/src/platz1de/EasyEdit/schematic/type/SpongeSchematic(142): pocketmine\utils\Binary::readUnsignedVarInt(string[19215] ................................................................................, int 19215)
  #1 /root/plugins/EasyEdit-master/src/platz1de/EasyEdit/schematic/SchematicFileAdapter(53): platz1de\EasyEdit\schematic\type\SpongeSchematic::readIntoSelection(object pocketmine\nbt\tag\CompoundTag#56870, object platz1de\EasyEdit\selection\DynamicBlockListSelection#57074)
  #2 /root/plugins/EasyEdit-master/src/platz1de/EasyEdit/task/schematic/SchematicLoadTask(37): platz1de\EasyEdit\schematic\SchematicFileAdapter::readIntoSelection(string[47] /root/plugin_data/EasyEdit/schematics/plottest1, object platz1de\EasyEdit\selection\DynamicBlockListSelection#57074)
  #3 /root/plugins/EasyEdit-master/src/platz1de/EasyEdit/thread/EditThread(79): platz1de\EasyEdit\task\schematic\SchematicLoadTask->executeInternal()
  #4 pmsrc/src/thread/CommonThreadPartsTrait(96): platz1de\EasyEdit\thread\EditThread->onRun()
  #5 (): pocketmine\thread\Thread->run()
--- End of exception information ---
[10:55:50.210] [EasyEdit editing thread/CRITICAL]: pocketmine\utils\BinaryDataException: "No bytes left in buffer" (EXCEPTION) in "pmsrc/vendor/pocketmine/binaryutils/src/Binary" at line 407
--- Stack trace ---
  #0 /root/plugins/EasyEdit-master/src/platz1de/EasyEdit/schematic/type/SpongeSchematic(142): pocketmine\utils\Binary::readUnsignedVarInt(string[19215] ................................................................................, int 19215)
  #1 /root/plugins/EasyEdit-master/src/platz1de/EasyEdit/schematic/SchematicFileAdapter(53): platz1de\EasyEdit\schematic\type\SpongeSchematic::readIntoSelection(object pocketmine\nbt\tag\CompoundTag#56048, object platz1de\EasyEdit\selection\DynamicBlockListSelection#56316)
  #2 /root/plugins/EasyEdit-master/src/platz1de/EasyEdit/task/schematic/SchematicLoadTask(37): platz1de\EasyEdit\schematic\SchematicFileAdapter::readIntoSelection(string[47] /root/plugin_data/EasyEdit/schematics/plottest1, object platz1de\EasyEdit\selection\DynamicBlockListSelection#56316)
  #3 /root/plugins/EasyEdit-master/src/platz1de/EasyEdit/thread/EditThread(79): platz1de\EasyEdit\task\schematic\SchematicLoadTask->executeInternal()
  #4 pmsrc/src/thread/CommonThreadPartsTrait(96): platz1de\EasyEdit\thread\EditThread->onRun()
  #5 (): pocketmine\thread\Thread->run()
--- End of exception information ---

When I tried to load the schematic I created with easy edit, it gave an error

**Comment by platz1de** [comment] 2023-07-09 11:11
This should be fixed in the newest dev build (Duplicate of #47)

**Closed by platz1de** 2023-07-09 11:11 UTC
